#!/usr/bin/env python3
"""
One-shot interactive setup for the Beeper -> Poke bridge.

Walks you through the whole thing: collects your credentials and writes `.env`,
installs dependencies, checks the iMessage handoff, points you at the Poke
tunnel, and (optionally) installs the always-on supervisor and starts the
bridge. Re-run any time; existing values are offered as defaults and steps are
safe to repeat.

    python configure.py

Uses only the standard library, so it runs before any dependencies are
installed; it shells out to `uv` (or a local venv) for everything that needs them.
"""

from __future__ import annotations

import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ENV_PATH = HERE / ".env"
IS_WINDOWS = os.name == "nt"

# (key, prompt, default, required, validator). The transport-specific block is
# chosen at runtime based on HANDOFF_TRANSPORT.
BASE_FIELDS = [
    ("OWNER_NAME", "Your name (how Poke refers to you in the gate prompt)", "", True, None),
    ("BEEPER_TOKEN", "Beeper Desktop API token  [Beeper -> Settings -> Developer]", "", True, None),
]
IMESSAGE_FIELDS = [
    ("POKE_IMESSAGE_HANDLE", "Poke's iMessage number/handle", "+16503347837", True, None),
]
TELEGRAM_FIELDS = [
    ("TELEGRAM_API_ID", "Telegram API ID  [https://my.telegram.org -> API development tools]", "", True, "int"),
    ("TELEGRAM_API_HASH", "Telegram API hash", "", True, None),
    ("POKE_TELEGRAM_USERNAME", "Poke bot username on Telegram", "interaction_poke_bot", False, None),
]
LLM_FIELDS = [
    ("LLM_PROVIDER", "Gatekeeper provider: auto | codex | openai", "auto", False, None),
    ("CODEX_MODEL", "Codex/subscription model (provider=codex/auto)", "gpt-5.4-mini", False, None),
    ("LLM_API_KEY", "LLM API key (blank = use Codex/ChatGPT subscription)", "", False, None),
    ("LLM_BASE_URL", "LLM base URL (API-key path)", "https://api.openai.com/v1", False, "url"),
    ("GATEKEEPER_MODEL", "Gatekeeper model (API-key path)", "gpt-5.4-mini", False, None),
]
EXTRA_FIELDS = [
    ("POKE_BEEPER_CHAT_ID", "Beeper room ID of the Poke chat to exclude from triage (optional)", "", False, None),
]

# Keys written commented-out when left blank.
BLANK_AS_COMMENT = {"POKE_BEEPER_CHAT_ID", "LLM_API_KEY"}


def fields_for(transport: str) -> list:
    block = TELEGRAM_FIELDS if transport == "telegram" else IMESSAGE_FIELDS
    return BASE_FIELDS + block + LLM_FIELDS + EXTRA_FIELDS


# ---------------------------------------------------------------------------
# Small prompt helpers
# ---------------------------------------------------------------------------

def yn(question: str, default_yes: bool = True) -> bool:
    suffix = "[Y/n]" if default_yes else "[y/N]"
    try:
        ans = input(f"{question} {suffix}: ").strip().lower()
    except (EOFError, KeyboardInterrupt):
        print()
        return False
    if not ans:
        return default_yes
    return ans in {"y", "yes"}


def section(title: str) -> None:
    print(f"\n--- {title} ---")


# ---------------------------------------------------------------------------
# .env
# ---------------------------------------------------------------------------

def load_existing() -> dict[str, str]:
    values: dict[str, str] = {}
    if ENV_PATH.exists():
        for line in ENV_PATH.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, _, v = line.partition("=")
            values[k.strip()] = v.strip()
    return values


def validate(value: str, kind: str | None) -> str | None:
    if kind == "int" and not value.isdigit():
        return "must be a number"
    if kind == "url" and not re.match(r"^https?://", value):
        return "must start with http:// or https://"
    return None


def ask_field(key: str, prompt: str, default: str, required: bool, kind: str | None) -> str:
    shown = default
    if default and key in {"BEEPER_TOKEN", "LLM_API_KEY"} and len(default) > 8:
        shown = default[:4] + "…" + default[-2:]
    suffix = f" [{shown}]" if default else (" (optional)" if not required else "")
    while True:
        raw = input(f"  {prompt}{suffix}: ").strip()
        value = raw or default
        if not value:
            if required:
                print("    -> required, please enter a value")
                continue
            return ""
        err = validate(value, kind)
        if err:
            print(f"    -> {err}")
            continue
        return value


def write_env(values: dict[str, str]) -> None:
    lines = ["# Beeper -> Poke bridge config. Generated by configure.py. Do not commit.", ""]
    for key, val in values.items():
        if val == "" and key in BLANK_AS_COMMENT:
            lines.append(f"# {key}=")
        else:
            lines.append(f"{key}={val}")
    ENV_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def collect_credentials() -> None:
    section("1. Credentials")
    if ENV_PATH.exists():
        print("Found an existing .env; current values are offered as defaults.")
    existing = load_existing()

    default_t = existing.get("HANDOFF_TRANSPORT", "imessage").lower()
    print("\n  Handoff transport -- how the bridge reaches Poke:")
    print("    1) imessage  (macOS Messages app, no login)")
    print("    2) telegram  (messages the Poke bot)")
    ans = input(f"  Choose [1/2] (default {'2' if default_t == 'telegram' else '1'}): ").strip()
    transport = "telegram" if ans == "2" else ("imessage" if ans == "1" else default_t)

    values = {"HANDOFF_TRANSPORT": transport}
    for key, prompt, default, required, kind in fields_for(transport):
        values[key] = ask_field(key, prompt, existing.get(key, default), required, kind)

    _check_provider_coherence(values)
    write_env(values)
    print(f"  Wrote {ENV_PATH}")


def _check_provider_coherence(values: dict) -> None:
    """Warn loudly if the gatekeeper provider can't actually work as configured."""
    provider = (values.get("LLM_PROVIDER") or "auto").lower()
    has_key = bool(values.get("LLM_API_KEY"))
    has_codex = (Path.home() / ".codex" / "auth.json").exists()
    if provider == "openai" and not has_key:
        print("  WARNING: LLM_PROVIDER=openai but no LLM_API_KEY -- the gate will fail. "
              "Set a key, or use provider 'codex'/'auto'.")
    elif provider == "codex" and not has_codex:
        print("  WARNING: LLM_PROVIDER=codex but ~/.codex/auth.json is missing -- run `codex login`.")
    elif provider == "auto" and not has_key and not has_codex:
        print("  WARNING: provider 'auto' but no LLM_API_KEY and no ~/.codex/auth.json -- "
              "run `codex login` or set a key, or the gate can't run.")


# ---------------------------------------------------------------------------
# Runtime: how to invoke python with dependencies available
# ---------------------------------------------------------------------------

def resolve_runner() -> list[str]:
    """Return the command prefix used to run the bridge with deps available."""
    if shutil.which("uv"):
        return ["uv", "run", "--with-requirements", "requirements.txt", "python"]

    # No uv: fall back to a local venv created with the system python.
    venv = HERE / ".venv"
    py = venv / ("Scripts/python.exe" if IS_WINDOWS else "bin/python")
    if not py.exists():
        print("  uv not found; creating a local .venv and installing dependencies…")
        subprocess.run([sys.executable, "-m", "venv", str(venv)], check=True)
        subprocess.run([str(py), "-m", "pip", "install", "-q", "-r", "requirements.txt"],
                       cwd=HERE, check=True)
    return [str(py)]


def ensure_dependencies(runner: list[str]) -> bool:
    section("2. Dependencies")
    print("  Resolving/installing dependencies (first run can take a minute)…")
    check = subprocess.run(
        runner + ["-c", "import telethon, openai, websockets, requests, dotenv; print('ok')"],
        cwd=HERE,
    )
    if check.returncode == 0:
        print("  Dependencies ready.")
        return True
    print("  Could not load dependencies. Fix the error above, then re-run.")
    return False


# ---------------------------------------------------------------------------
# Steps that use the runner
# ---------------------------------------------------------------------------

def transport_setup(runner: list[str]) -> None:
    transport = load_existing().get("HANDOFF_TRANSPORT", "imessage").lower()
    if transport == "telegram":
        section("3. Telegram login")
        print("  One-time: Telegram will ask for your phone number and a login code.")
        if not yn("  Authorize Telegram now?"):
            print("  Skipped. Run later:  " + " ".join(runner) + " bridge.py --login")
            return
        subprocess.run(runner + ["bridge.py", "--login"], cwd=HERE)
    else:
        section("3. iMessage handoff")
        if sys.platform != "darwin":
            print("  WARNING: the iMessage handoff needs macOS with Messages signed in to")
            print("  iMessage. This machine isn't macOS, so the bridge can't text Poke here.")
            return
        print("  The bridge texts Poke through the macOS Messages app -- no login needed.")
        print("  Make sure Messages is open and signed in to iMessage.")
        if not yn("  Send a test handoff to Poke now?"):
            print("  Skipped. Test later:  " + " ".join(runner) + " bridge.py --test")
            return
        subprocess.run(runner + ["bridge.py", "--test"], cwd=HERE)


def tunnel_setup() -> None:
    section("4. Let Poke read your chats (the tunnel)")
    print("  For Poke to draft replies it needs your Beeper MCP. The official way is")
    print("  the Poke CLI tunnel (https://poke.com/docs/mcp-servers). Beeper Desktop")
    print("  must be running. Leave the tunnel running alongside the bridge:\n")
    cmd = 'npx poke@latest tunnel http://localhost:23373/v0/mcp -n "Beeper Desktop"'
    print(f"      {cmd}\n")
    if shutil.which("npx") and yn("  Launch the tunnel now in a new window?", default_yes=False):
        try:
            if IS_WINDOWS:
                subprocess.Popen(["cmd", "/c", "start", "", "cmd", "/k", cmd], cwd=HERE)
            else:
                subprocess.Popen(cmd, shell=True, cwd=HERE)
            print("  Tunnel launching. Keep that window open.")
        except Exception as e:
            print(f"  Could not auto-launch ({e}); run the command above yourself.")
    else:
        print("  Run that command in a separate terminal when you're ready.")


def install_always_on(runner: list[str]) -> None:
    section("5. Keep it running (auto-start + auto-restart)")
    if IS_WINDOWS:
        vbs = HERE / "run-watchdog-hidden.vbs"
        print("  Registers a per-minute Task Scheduler job that starts the bridge at")
        print("  logon and relaunches it if it dies (via watchdog.ps1).")
        if not yn("  Install the Windows watchdog task now?"):
            print("  Skipped. See README -> Keeping it running.")
            return
        user = os.environ.get("USERNAME", "")
        cmd = [
            "schtasks", "/Create", "/TN", "PokeBridge",
            "/TR", f'wscript.exe "{vbs}"',
            "/SC", "MINUTE", "/MO", "1", "/IT", "/RL", "LIMITED", "/F",
        ]
        if user:
            cmd += ["/RU", user]
        result = subprocess.run(cmd)
        if result.returncode == 0:
            print("  Installed task 'PokeBridge'. It will keep the bridge alive.")
        else:
            print("  Task registration failed (see above). You can register it manually per the README.")
    else:
        print("  On Linux/macOS use your init system (no extra files needed):")
        print("    - Linux: a systemd user unit with Restart=always")
        print("    - macOS: a launchd agent with KeepAlive")
        print("  The README 'Keeping it running' section has copy-paste templates.")


def start_now(runner: list[str]) -> None:
    section("6. Start the bridge")
    if not yn("  Start the bridge now?"):
        print("  Skipped. Start later:  " + " ".join(runner) + " bridge.py")
        return
    if IS_WINDOWS and shutil.which("schtasks"):
        # If the watchdog task exists, let it own the process; otherwise run detached.
        q = subprocess.run(["schtasks", "/Query", "/TN", "PokeBridge"],
                            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        if q.returncode == 0:
            subprocess.run(["schtasks", "/Run", "/TN", "PokeBridge"],
                           stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            print("  Started via the watchdog task. Check bridge.log for progress.")
            return
    try:
        subprocess.Popen(runner + ["bridge.py"], cwd=HERE)
        print("  Bridge starting in the background. Check bridge.log for progress.")
    except Exception as e:
        print(f"  Could not start ({e}); run it yourself: " + " ".join(runner) + " bridge.py")


# ---------------------------------------------------------------------------

def main() -> int:
    print("\n=== Beeper -> Poke bridge setup ===")
    print("Press Enter to accept a [default]. Ctrl+C to stop any time.\n")

    collect_credentials()

    runner = resolve_runner()
    if not ensure_dependencies(runner):
        return 1

    transport_setup(runner)
    tunnel_setup()
    install_always_on(runner)
    start_now(runner)

    print("\nDone. The bridge stays silent until a message clears the gate.")
    print("Logs: bridge.log   |   Config: .env   |   Docs: README.md\n")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except KeyboardInterrupt:
        print("\nCancelled.")
        raise SystemExit(1)
