#!/usr/bin/env python3
"""
Interactive setup for the Beeper -> Poke bridge.

Prompts for your credentials and writes a `.env` file -- no manual editing.
Re-run any time to update values (existing ones are offered as defaults).

    python configure.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ENV_PATH = HERE / ".env"

# (key, prompt, default, required, validator)
FIELDS = [
    ("OWNER_NAME", "Your name (how Poke refers to you in the gate prompt)", "", True, None),
    ("BEEPER_TOKEN", "Beeper Desktop API token  [Beeper -> Settings -> Developer]", "", True, None),
    ("TELEGRAM_API_ID", "Telegram API ID  [https://my.telegram.org -> API development tools]", "", True, "int"),
    ("TELEGRAM_API_HASH", "Telegram API hash", "", True, None),
    ("LLM_API_KEY", "LLM provider API key (OpenAI-compatible)", "", True, None),
    ("LLM_BASE_URL", "LLM base URL", "https://api.openai.com/v1", False, "url"),
    ("GATEKEEPER_MODEL", "Gatekeeper model (use a cheap, fast one)", "gpt-4o-mini", False, None),
    ("POKE_BEEPER_CHAT_ID", "Beeper room ID of your Telegram<->Poke chat (optional; see README)", "", False, None),
]


def load_existing() -> dict[str, str]:
    values: dict[str, str] = {}
    if ENV_PATH.exists():
        for line in ENV_PATH.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, _, v = line.partition("=")
            values[k.strip()] = v.strip()
    return values


def validate(value: str, kind: str | None) -> str | None:
    """Return an error string if invalid, else None."""
    if kind == "int" and not value.isdigit():
        return "must be a number"
    if kind == "url" and not re.match(r"^https?://", value):
        return "must start with http:// or https://"
    return None


def ask(key: str, prompt: str, default: str, required: bool, kind: str | None) -> str:
    shown_default = default
    # Mask long secrets in the displayed default so they aren't echoed in full.
    if default and key in {"BEEPER_TOKEN", "TELEGRAM_API_HASH", "LLM_API_KEY"} and len(default) > 8:
        shown_default = default[:4] + "…" + default[-2:]
    suffix = f" [{shown_default}]" if default else (" (optional)" if not required else "")
    while True:
        raw = input(f"  {prompt}{suffix}: ").strip()
        value = raw or default
        if not value:
            if required:
                print("    -> required, please enter a value")
                continue
            return ""
        err = validate(value, kind)
        if err:
            print(f"    -> {err}")
            continue
        return value


def write_env(values: dict[str, str]) -> None:
    lines = [
        "# Beeper -> Poke bridge config. Generated by configure.py. Do not commit.",
        "",
    ]
    for key, _, _, _, _ in FIELDS:
        val = values.get(key, "")
        if val == "" and key in {"POKE_BEEPER_CHAT_ID"}:
            lines.append(f"# {key}=")
        else:
            lines.append(f"{key}={val}")
    ENV_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    print("\n=== Beeper -> Poke bridge setup ===\n")
    if ENV_PATH.exists():
        print(f"Found existing {ENV_PATH.name}; current values are offered as defaults.\n")
    existing = load_existing()

    values: dict[str, str] = {}
    for key, prompt, default, required, kind in FIELDS:
        values[key] = ask(key, prompt, existing.get(key, default), required, kind)

    write_env(values)
    print(f"\nWrote {ENV_PATH}")

    print("\nNext steps:")
    print("  1) Authorize Telegram (one-time, asks for phone + login code):")
    print("       python bridge.py --login")
    print("  2) Start the bridge:")
    print("       python bridge.py        (or run-bridge.bat / ./run-bridge.sh)")
    print("\nSee README.md to keep it running in the background.\n")

    try:
        if input("Run the Telegram login now? [y/N]: ").strip().lower() in {"y", "yes"}:
            import subprocess
            subprocess.run([sys.executable, str(HERE / "bridge.py"), "--login"], check=False)
    except (EOFError, KeyboardInterrupt):
        pass
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except KeyboardInterrupt:
        print("\nCancelled.")
        raise SystemExit(1)
